"""
ClinicalTable Pro — PDF Export (fpdf2)

Renders the Table 1 result into a publication-quality PDF.
Uses fpdf2 (pure Python, no system dependencies).
"""

from __future__ import annotations

import io
from typing import Any

from fpdf import FPDF


class JournalTablePDF(FPDF):
    """Custom PDF class for journal-style table output."""

    def __init__(self):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Times", "I", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Generated by ClinicalTable Pro", align="R")


def sanitize_text(text: str) -> str:
    """Replace non-latin-1 characters with ASCII approximations to avoid FPDF crashes."""
    if not isinstance(text, str):
        return str(text)
    
    replacements = {
        '\u2020': '*',     # Dagger
        '\u2021': '**',    # Double dagger
        '\u2264': '<=',    # Less than or equal
        '\u2265': '>=',    # Greater than or equal
        '\u2013': '-',     # En-dash
        '\u2014': '-',     # Em-dash
        '\u2018': "'",     # Single quote
        '\u2019': "'",     # Single quote
        '\u201c': '"',     # Double quote
        '\u201d': '"',     # Double quote
        '\u03bc': '\u00b5',# Greek mu to latin-1 micro
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
        
    return text.encode('latin-1', 'replace').decode('latin-1')

def export_pdf(table_data: dict[str, Any], title: str = "Table 1") -> bytes:
    """
    Generate PDF bytes from table data.

    Parameters
    ----------
    table_data : dict
        Output from generate_table_one().
    title : str
        Table title/number.

    Returns
    -------
    bytes : PDF file content.
    """

    columns = table_data["columns"]
    rows = table_data["rows"]
    footnotes = table_data.get("footnotes", [])
    stat_notes = table_data.get("stats_method_notes", [])

    pdf = JournalTablePDF()
    pdf.add_page()

    # Title
    pdf.set_font("Times", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, sanitize_text(f"{title}. Baseline Characteristics of Study Participants"), ln=True)
    pdf.ln(4)

    # Calculate column widths
    page_width = pdf.w - pdf.l_margin - pdf.r_margin
    n_cols = len(columns)

    # First column (variable names) gets more space
    first_col_width = page_width * 0.30
    remaining_width = page_width - first_col_width
    other_col_width = remaining_width / max(n_cols - 1, 1)

    col_widths = [first_col_width] + [other_col_width] * (n_cols - 1)

    # Top border (thick)
    y_pos = pdf.get_y()
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, y_pos, pdf.l_margin + page_width, y_pos)
    pdf.ln(1)

    # Header row
    pdf.set_font("Times", "B", 9)
    cell_height = 6
    for i, col in enumerate(columns):
        align = "R" if col == "P-value" else "L"
        pdf.cell(col_widths[i], cell_height, sanitize_text(col), border=0, align=align)
    pdf.ln()

    # Header bottom border (thin)
    y_pos = pdf.get_y()
    pdf.set_line_width(0.2)
    pdf.line(pdf.l_margin, y_pos, pdf.l_margin + page_width, y_pos)
    pdf.ln(1)

    # Data rows
    pdf.set_font("Times", "", 9)
    for row in rows:
        row_type = row.get("type", "")
        variable = row.get("variable", "")
        values = row.get("values", {})

        # Variable name cell
        if row_type == "category_header":
            pdf.set_font("Times", "BI", 9)
            pdf.cell(col_widths[0], cell_height, sanitize_text(variable), border=0)
        elif row_type == "category_value":
            pdf.set_font("Times", "", 9)
            pdf.cell(col_widths[0], cell_height, sanitize_text(f"    {variable.strip()}"), border=0)
        else:
            pdf.set_font("Times", "", 9)
            pdf.cell(col_widths[0], cell_height, sanitize_text(variable), border=0)

        # Value cells
        pdf.set_font("Courier", "", 8)
        for i, col in enumerate(columns[1:], 1):
            if col == "P-value":
                val = str(values.get("p_value", ""))
                align = "R"
            else:
                group_name = col.split(" (n=")[0] if " (n=" in col else col.split(" (N=")[0]
                val = str(values.get(group_name, values.get(col, "")))
                align = "L"
            pdf.cell(col_widths[i], cell_height, sanitize_text(val), border=0, align=align)

        pdf.ln()

    # Bottom border (thick)
    y_pos = pdf.get_y()
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, y_pos, pdf.l_margin + page_width, y_pos)
    pdf.ln(3)

    # Footnotes
    all_notes = footnotes + stat_notes
    if all_notes:
        pdf.set_font("Times", "I", 8)
        pdf.set_text_color(50, 50, 50)
        for note in all_notes:
            pdf.multi_cell(page_width, 4, sanitize_text(note))
            pdf.ln(1)

    # Output to bytes
    return pdf.output()
